# Generated by Django 6.1.1 on 2026-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_routehistory_alter_edges_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routehistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
